version: "3"

services:

  tomcat:
    image: "tomcat:8.0.47-jre8-alpine"
    volumes:
      - ./sample-issue-tracker/target/sample-issue-tracker:/usr/local/tomcat/webapps/sample-issue-tracker
    ports:
      - "8080:8080"
